<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this item?' => 'Apakah Anda yakin hendak menghapus item ini?',
    'Are you sure to restore this item?' => 'Apakah Anda yakin akan mengembalikan item ini?',
    'Cancel' => 'Batal',
    'Create' => 'Tambah',
    'Delete' => 'Hapus',
    'Edit' => 'Ubah',
    'First' => 'Pertama',
    'Full list' => 'Daftar lengkap',
    'Instalation Distributions' => 'Instalasi Distribusi',
    'Instalation Generators' => 'Instalasi Generator',
    'Instalation Transmissions' => 'Instalasi Transmisi',
    'Instalation Utilizations' => 'Instalasi Pemanfaatan',
    'Last' => 'Terakhir',
    'List' => 'Daftar',
    'List All' => 'Semua baris',
    'New' => 'Baru',
    'New Instalation Distribution' => 'Instalasi Distribusi Baru',
    'New Instalation Generator' => 'Instalasi Generator Baru',
    'New Instalation Transmission' => 'Instalasi Transmisi Baru',
    'New Instalation Utilization' => 'Instalasi Pemanfaatan Baru',
    'New Submission' => 'Permohonan Baru',
    'Reset' => 'Reset',
    'Restore' => 'Kembalikan',
    'Save' => 'Simpan',
    'Search' => 'Cari',
    'Select' => 'Pilih',
    'Submissions' => 'Permohonan',
    'View' => 'Lihat',
];
