<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Alamat',
    'Agenda Number' => 'Nomor Agenda',
    'Bussiness Type' => 'Tipe Bisnis',
    'Bussiness Types' => 'Tipe Bisnis',
    'City' => 'Kota',
    'Country' => 'Negara',
    'Created At' => 'Ditambahkan pada',
    'Created By' => 'Ditambahkan oleh',
    'Deleted At' => 'Dihapus pada',
    'Deleted By' => 'Dihapus oleh',
    'Email' => 'Surel',
    'Examination' => 'Pemeriksaan',
    'Examination Date' => 'Tanggal Pemeriksaan',
    'ID' => 'ID',
    'Instalation' => 'Instalasi',
    'Instalation Name' => 'Nama Instalasi',
    'Is Deleted' => 'Terhapus',
    'Latitude' => 'Latitude',
    'Location' => 'Lokasi',
    'Longitude' => 'Longitude',
    'Name' => 'Nama',
    'New' => 'Baru',
    'New Bussiness Type' => 'Tipe Bisnis Baru',
    'New Owner' => 'Pemilik Baru',
    'New Sbu' => 'SBU',
    'New Submission' => 'Permohonan Baru',
    'New Technical Personel' => 'Tenaga Teknis Baru',
    'New Technical Pic' => 'PJ Teknis Baru',
    'Owner' => 'Pemilik',
    'Owners' => 'Pemilik',
    'Phone' => 'Telepon',
    'Progress Status' => 'Status Proses',
    'Province' => 'Provinsi',
    'Regency' => 'Kabupaten',
    'Registered At' => 'Teregistrasi Pada',
    'Registered By' => 'Teregistrasi Oleh',
    'Registering At' => 'Registrasi Pada',
    'Registering By' => 'Registrasi Oleh',
    'Report File' => 'Berkas Laporan',
    'Report Number' => 'Nomor Laporan',
    'Requested At' => 'Permohonan Pada',
    'Requested By' => 'Permohonan Oleh',
    'SBU' => 'SBU',
    'SBUs' => 'SBU',
    'Submission' => 'Permohonan',
    'Submissions' => 'Permohonan',
    'Technical PIC' => 'PJ Teknis',
    'Technical PICs' => 'PJ Teknis',
    'Technical Personel' => 'Tenaga Teknis',
    'Technical Personels' => 'Tenaga Teknis',
    'Updated At' => 'Diperbarui pada',
    'Updated By' => 'Diperbarui oleh',
];
