<?php

use app\models\InstalationGenerator;
use dmstr\bootstrap\Tabs;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model InstalationGenerator */

$this->title = $model->aliasModel.' | '.$model->submission_id;
$this->params['breadcrumbs'][] = ['label' => $model->getAliasModel(TRUE), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => '#'.$model->submission_id, 'url' => ['view', 'submission_id' => $model->submission_id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud instalation-generator-view">

    <h1>
        <?= $model->aliasModel ?>
        <small>
            <?= Html::encode($model->submission_id) ?>
        </small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-right'>
            <?=
            ButtonDropdown::widget([
                'label' => Yii::t('cruds', 'Edit'),
                'tagName' => 'a',
                'split' => true,
                'options' => [
                    'href' => ['update', 'submission_id' => $model->submission_id],
                    'class' => 'btn btn-info',
                ],
                'dropdown' => [
                    'encodeLabels' => FALSE,
                    'options' => [
                        'class' => 'dropdown-menu-right',
                    ],
                    'items' => [
                        '<li role="presentation" class="divider"></li>',
                        [
                            'label' => '<span class="glyphicon glyphicon-list"></span> '.Yii::t('cruds', 'Full list'),
                            'url' => ['index'],
                        ],
                        [
                            'label' => '<span class="glyphicon glyphicon-plus"></span> '.Yii::t('cruds', 'New'),
                            'url' => ['create'],
                        ],
                        '<li role="presentation" class="divider"></li>',
                        [
                            'label' => '<span class="glyphicon glyphicon-trash"></span> '.Yii::t('cruds', 'Delete'),
                            'url' => ['delete', 'submission_id' => $model->submission_id],
                            'linkOptions' => [
                                'data-confirm' => Yii::t('cruds', 'Are you sure to delete this item?'),
                                'data-method' => 'post',
                                'data-pjax' => FALSE,
                                'class' => 'label label-danger',
                            ],
                        ],
                    ],
                ],
            ]);
            ?>
        </div>

    </div>

    <hr/>

    
    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'submission_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'submission.id', '<span class="label label-warning">?</span>'),
            ],
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'subtype_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'subtype.name', '<span class="label label-warning">?</span>'),
            ],
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'fuel_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'fuel.name', '<span class="label label-warning">?</span>'),
            ],
            'module_quantity',
            'inverter_quantity',
            'calorific_value_file_id',
            'capacity',
            'test_capacity',
            'capacity_unit',
            'test_capacity_unit',
            'unit_number',
            'turbine_serial_number',
            'generator_serial_number',
            'each_module_capacity',
            'each_inverter_capacity',
            'calorific_value',
            'fuel_consumption_hhv',
            'fuel_consumption_lhv',
            'sfc',
            'unit',
        ],
    ]);
    ?>

    
    <hr/>
    

    <hr/>

</div>
