<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use dmstr\bootstrap\Tabs;

/* @var $this yii\web\View  */
/* @var $form yii\widgets\ActiveForm  */
/* @var $model app\models\SubmissionForm  */
?>

<div class="submission-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'Submission',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
    ]);
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


			<!-- attribute progress_status -->
            <?= $form->field($model, 'progress_status')->textInput() ?>

			<!-- attribute owner_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'owner_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Owner::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['owner_id'])),
    ]
); ?>

			<!-- attribute instalation_country_id -->
            <?= $form->field($model, 'instalation_country_id')->textInput(['maxlength' => true]) ?>

			<!-- attribute instalation_province_id -->
            <?= $form->field($model, 'instalation_province_id')->textInput(['maxlength' => true]) ?>

			<!-- attribute instalation_regency_id -->
            <?= $form->field($model, 'instalation_regency_id')->textInput(['maxlength' => true]) ?>

			<!-- attribute bussiness_type_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'bussiness_type_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\BussinessType::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['bussiness_type_id'])),
    ]
); ?>

			<!-- attribute sbu_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'sbu_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Sbu::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['sbu_id'])),
    ]
); ?>

			<!-- attribute technical_pic_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'technical_pic_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\TechnicalPic::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['technical_pic_id'])),
    ]
); ?>

			<!-- attribute technical_personel_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'technical_personel_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\TechnicalPersonel::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['technical_personel_id'])),
    ]
); ?>

			<!-- attribute instalation_location -->
            <?= $form->field($model, 'instalation_location')->textarea(['rows' => 6]) ?>

			<!-- attribute instalation_latitude -->
            <?= $form->field($model, 'instalation_latitude')->textInput(['maxlength' => true]) ?>

			<!-- attribute instalation_longitude -->
            <?= $form->field($model, 'instalation_longitude')->textInput(['maxlength' => true]) ?>

			<!-- attribute agenda_number -->
            <?= $form->field($model, 'agenda_number')->textInput(['maxlength' => true]) ?>

			<!-- attribute report_number -->
            <?= $form->field($model, 'report_number')->textInput(['maxlength' => true]) ?>

			<!-- attribute instalation_name -->
            <?= $form->field($model, 'instalation_name')->textInput(['maxlength' => true]) ?>

			<!-- attribute examination_date -->
            <?= $form->field($model, 'examination_date')->textInput() ?>
            
        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => $model->aliasModel,
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>

        <hr/>

        <?=  $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

        </div>

    <?php ActiveForm::end(); ?>

</div>

