<?php

use app\models\Submission;
use dmstr\bootstrap\Tabs;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model Submission */

$this->title = $model->aliasModel.' | '.$model->id;
$this->params['breadcrumbs'][] = ['label' => $model->getAliasModel(TRUE), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => '#'.$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud submission-view">

    <h1>
        <?=  $model->aliasModel ?>
        <small>            
            #<?=  $model->id ?>
            
            <?php if ($model->is_deleted): ?>
                <span class="badge">deleted</span>
            <?php endif; ?>  
            
        </small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-right'>
            <?=
            ButtonDropdown::widget([
                'label' => Yii::t('cruds', 'Edit'),
                'tagName' => 'a',
                'split' => true,
                'options' => [
                    'href' => ['update', 'id' => $model->id],
                    'class' => 'btn btn-info',
                ],
                'dropdown' => [
                    'encodeLabels' => FALSE,
                    'items' => [
                        '<li role="presentation" class="divider"></li>',
                        [
                            'label' => '<span class="glyphicon glyphicon-list"></span> '.Yii::t('cruds', 'Full list'),
                            'url' => ['index'],
                        ],
                        [
                            'label' => '<span class="glyphicon glyphicon-plus"></span> '.Yii::t('cruds', 'New'),
                            'url' => ['create'],
                        ],
                        '<li role="presentation" class="divider"></li>',
                        [
                            'label' => '<span class="glyphicon glyphicon-trash"></span> '.Yii::t('cruds', 'Delete'),
                            'url' => ['delete', 'id' => $model->id],
                            'linkOptions' => [
                                'data-confirm' => Yii::t('cruds', 'Are you sure to delete this item?'),
                                'data-method' => 'post',
                                'data-pjax' => FALSE,
                                'class' => 'label label-danger',
                            ],
                            'visible' => ($model->is_deleted == FALSE),
                        ],
                        [
                            'label' => '<span class="glyphicon glyphicon-floppy-open"></span> '.Yii::t('cruds', 'Restore'),
                            'url' => ['delete', 'id' => $model->id],
                            'linkOptions' => [
                                'data-confirm' => Yii::t('cruds', 'Are you sure to restore this item?'),
                                'data-method' => 'post',
                                'data-pjax' => FALSE,
                                'class' => 'label label-info',
                            ],
                            'visible' => ($model->is_deleted),
            
                        ],
                    ],
                ],
            ]);
            ?>
        </div>

    </div>

    <hr/>

    
    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
                    'progress_status',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'owner_id',
    'value' => ($model->owner ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['owner/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->owner->name, ['owner/view', 'id' => $model->owner->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Submission'=>['owner_id' => $model->owner_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
                    'instalation_country_id',
                    'instalation_province_id',
                    'instalation_regency_id',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'bussiness_type_id',
    'value' => ($model->bussinessType ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['bussiness-type/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->bussinessType->name, ['bussiness-type/view', 'id' => $model->bussinessType->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Submission'=>['bussiness_type_id' => $model->bussiness_type_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'sbu_id',
    'value' => ($model->sbu ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['sbu/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->sbu->name, ['sbu/view', 'id' => $model->sbu->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Submission'=>['sbu_id' => $model->sbu_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'technical_pic_id',
    'value' => ($model->technicalPic ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['technical-pic/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->technicalPic->name, ['technical-pic/view', 'id' => $model->technicalPic->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Submission'=>['technical_pic_id' => $model->technical_pic_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'technical_personel_id',
    'value' => ($model->technicalPersonel ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['technical-personel/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->technicalPersonel->name, ['technical-personel/view', 'id' => $model->technicalPersonel->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Submission'=>['technical_personel_id' => $model->technical_personel_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
                    'instalation_location:ntext',
                    'instalation_latitude',
                    'instalation_longitude',
                    'agenda_number',
                    'report_number',
                    'instalation_name',
                    'examination_date',
        ],
    ]);
    ?>

    
    <hr/>
    
<?php $this->beginBlock('CreatedBy'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>

            <?= 
            Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All') . ' Created By',
                ['user/index'],
                ['class'=>'btn text-muted btn-xs']
            );
            ?>

          
            <?= 
            Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New') . ' Created By',
                ['user/create', 'User' => ['created_by' => $model->id]],
                ['class'=>'btn btn-success btn-xs']
            );
            ?>
        </div>
    </div>
<?php Pjax::begin(['id'=>'pjax-CreatedBy', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-CreatedBy ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getCreatedBy(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-createdby',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'user' . '/' . $action;
        $params['User'] = ['created_by' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'user'
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'id',
    'value' => function ($model) {
        if ($rel = $model->id0) {
            return Html::a($rel->name, ['profile/view', 'user_id' => $rel->user_id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'username',
        'email:email',
        'password_hash',
        'auth_key',
        'confirmed_at',
        'unconfirmed_email:email',
        'blocked_at',
        'registration_ip',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('UpdatedBy'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>

            <?= 
            Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All') . ' Updated By',
                ['user/index'],
                ['class'=>'btn text-muted btn-xs']
            );
            ?>

          
            <?= 
            Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New') . ' Updated By',
                ['user/create', 'User' => ['updated_by' => $model->id]],
                ['class'=>'btn btn-success btn-xs']
            );
            ?>
        </div>
    </div>
<?php Pjax::begin(['id'=>'pjax-UpdatedBy', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-UpdatedBy ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getUpdatedBy(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-updatedby',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'user' . '/' . $action;
        $params['User'] = ['updated_by' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'user'
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'id',
    'value' => function ($model) {
        if ($rel = $model->id0) {
            return Html::a($rel->name, ['profile/view', 'user_id' => $rel->user_id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'username',
        'email:email',
        'password_hash',
        'auth_key',
        'confirmed_at',
        'unconfirmed_email:email',
        'blocked_at',
        'registration_ip',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('DeletedBy'); ?>
    <div style='position: relative'>
        <div style='position:absolute; right: 0px; top: 0px;'>

            <?= 
            Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('cruds', 'List All') . ' Deleted By',
                ['user/index'],
                ['class'=>'btn text-muted btn-xs']
            );
            ?>

          
            <?= 
            Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New') . ' Deleted By',
                ['user/create', 'User' => ['deleted_by' => $model->id]],
                ['class'=>'btn btn-success btn-xs']
            );
            ?>
        </div>
    </div>
<?php Pjax::begin(['id'=>'pjax-DeletedBy', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-DeletedBy ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getDeletedBy(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-deletedby',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('cruds', 'First'),
        'lastPageLabel'  => Yii::t('cruds', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'user' . '/' . $action;
        $params['User'] = ['deleted_by' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'user'
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'id',
    'value' => function ($model) {
        if ($rel = $model->id0) {
            return Html::a($rel->name, ['profile/view', 'user_id' => $rel->user_id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'username',
        'email:email',
        'password_hash',
        'auth_key',
        'confirmed_at',
        'unconfirmed_email:email',
        'blocked_at',
        'registration_ip',
]
])
 . '</div>' 
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>



    <?= 
    Tabs::widget([
        'id' => 'relation-tabs',
        'encodeLabels' => false,
        'items' => [
                [
                    'content' => $this->blocks['CreatedBy'],
                    'label'   => '<small>Created By <span class="badge badge-default">'. $model->getCreatedBy()->count() . '</span></small>',
                    #'active'  => false,
                ],
                [
                    'content' => $this->blocks['UpdatedBy'],
                    'label'   => '<small>Updated By <span class="badge badge-default">'. $model->getUpdatedBy()->count() . '</span></small>',
                    #'active'  => false,
                ],
                [
                    'content' => $this->blocks['DeletedBy'],
                    'label'   => '<small>Deleted By <span class="badge badge-default">'. $model->getDeletedBy()->count() . '</span></small>',
                    #'active'  => false,
                ],

        ],
    ]);
    ?>


    <hr/><br/>

</div>
