#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

// load host config

$host_config_path = __DIR__.'/../config/host/console.php';
$host_config_exist = file_exists($host_config_path);

if ($host_config_exist) {
    $host_config = require $host_config_path;
    $config = yii\helpers\ArrayHelper::merge($config, $host_config);
}

// run app

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
