<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use dmstr\bootstrap\Tabs;

/* @var $this yii\web\View  */
/* @var $form yii\widgets\ActiveForm  */
/* @var $model app\models\InstalationUtilizationForm  */
?>

<div class="instalation-utilization-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'InstalationUtilization',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
    ]);
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


			<!-- attribute submission_id -->
            <?= 
                // generated by app\generator\crud\providers\RelationProvider::activeField
                $form
                ->field($model, 'submission_id')
                ->dropDownList(
                    \yii\helpers\ArrayHelper::map(\app\models\Submission::find()->all(), 'id', 'id'),
                    [
                        'prompt' => Yii::t('cruds', 'Select'),
                        'disabled' => (isset($relAttributes) && isset($relAttributes['submission_id'])),
                    ]
                ); ?>

			<!-- attribute subtype_id -->
            <?= 
                // generated by app\generator\crud\providers\RelationProvider::activeField
                $form
                ->field($model, 'subtype_id')
                ->dropDownList(
                    \yii\helpers\ArrayHelper::map(\app\models\InstalationSubtype::find()->all(), 'id', 'name'),
                    [
                        'prompt' => Yii::t('cruds', 'Select'),
                        'disabled' => (isset($relAttributes) && isset($relAttributes['subtype_id'])),
                    ]
                ); ?>

			<!-- attribute medium_voltage_connecting_panel_quantity -->
            <?= $form->field($model, 'medium_voltage_connecting_panel_quantity')->textInput() ?>

			<!-- attribute low_voltage_connecting_panel_quantity -->
            <?= $form->field($model, 'low_voltage_connecting_panel_quantity')->textInput() ?>

			<!-- attribute substation_transformer_kva -->
            <?= $form->field($model, 'substation_transformer_kva')->textInput(['maxlength' => true]) ?>

			<!-- attribute connected_power_kva -->
            <?= $form->field($model, 'connected_power_kva')->textInput(['maxlength' => true]) ?>

			<!-- attribute electricity_provider -->
            <?= $form->field($model, 'electricity_provider')->textInput(['maxlength' => true]) ?>

        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget([
            'encodeLabels' => false,
            'items' => [
                [
                    'label' => $model->aliasModel,
                    'content' => $this->blocks['main'],
                    'active' => true,
                ],
            ],
        ]);
        ?>

        <hr/>

        <?= $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
            [
            'id' => 'save-'.$model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

        </div>

    <?php ActiveForm::end(); ?>

</div>

