<?php

use app\models\InstalationUtilization;
use dmstr\bootstrap\Tabs;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model InstalationUtilization */
?>
<div class="instalation-utilization-view">

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'subtype_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'subtype.name', '<span class="label label-warning">?</span>'),
            ],
            'medium_voltage_connecting_panel_quantity',
            'low_voltage_connecting_panel_quantity',
            'substation_transformer_kva',
            'connected_power_kva',
            'electricity_provider',
        ],
    ]);
    ?>

</div>
