<?php

use app\dictionaries\OwnershipStatus;
use app\models\InstalationDistribution;
use dmstr\bootstrap\Tabs;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model InstalationDistribution */
?>
<div class="instalation-distribution-view">

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'subtype_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'subtype.name', '<span class="label label-warning">?</span>'),
            ],
            [
                'attribute' => 'ownership_status',
                'format' => 'html',
                'value' => OwnershipStatus::getLabel($model->ownership_status),
            ],
            [
                'attribute' => 'voltage_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'voltage.name', '<span class="label label-warning">?</span>'),
            ],
            'substation_quantity',
            'panel_quantity',
            'jtm_length_kms',
            'sktm_length_ms',
            'sutm_length_ms',
            'jtr_length_kms',
            'sktr_length_ms',
            'sutr_length_ms',
            'substation_capacity_kva',
            'short_circuit_capacity_a',
            'distribution_region',
        ],
    ]);
    ?>

</div>
