<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Type ID' => 'ID Tipe',
    'Type Label' => 'Label Tipe',
    'Abbreviation' => 'Singkatan',
    'Counter' => 'Penghitung',
    'Counters' => 'Hitungan',
    'Created At' => 'Dibuat pada',
    'Created By' => 'Dibuat oleh',
    'ID' => 'ID',
    'Language' => 'Bahasa',
    'Latitude' => 'Latitude',
    'Longitude' => 'Longitude',
    'Name' => 'Nama',
    'Place' => 'Lokasi',
    'Place ID' => 'ID Lokasi',
    'Place Label' => 'Label Lokasi',
    'Places' => 'Lokasi',
    'Quantity' => 'Cacah',
    'Search Name' => 'Cari Nama',
    'Sublocation' => 'Sublokasi',
    'Sublocation Of' => 'Bagian dari',
    'Sublocations' => 'Sublokasi',
    'Sublocations Counters' => 'Penghitung Sublokasi',
    'Translation' => 'Terjemahan',
    'Translations' => 'Terjemahan',
    'Type' => 'Tipe',
    'Types' => 'Tipe',
    'Updated At' => 'Diperbarui Pada',
    'Updated By' => 'Diperbarui Oleh',
];
