<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use dmstr\bootstrap\Tabs;

/* @var $this yii\web\View  */
/* @var $form yii\widgets\ActiveForm  */
/* @var $model app\models\TechnicalPersonelForm  */
?>

<div class="technical-personel-form">

    <?php
    $form = ActiveForm::begin([
            'id' => 'TechnicalPersonel',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
    ]);
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


			<!-- attribute address -->
            <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>

			<!-- attribute country_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'country_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(fredyns\region\models\Area::find()->all(), 'id', 'label'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['country_id'])),
    ]
); ?>

			<!-- attribute province_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'province_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(fredyns\region\models\Area::find()->all(), 'id', 'label'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['province_id'])),
    ]
); ?>

			<!-- attribute regency_id -->
            <?= // generated by app\generator\crud\providers\RelationProvider::activeField
$form->field($model, 'regency_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(fredyns\region\models\Area::find()->all(), 'id', 'label'),
    [
        'prompt' => Yii::t('cruds', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['regency_id'])),
    ]
); ?>

			<!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

			<!-- attribute phone -->
            <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

			<!-- attribute email -->
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            
        </p>

        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => $model->aliasModel,
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>

        <hr/>

        <?= $form->errorSummary($model); ?>

        <?=
        Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
            [
            'id' => 'save-'.$model->formName(),
            'class' => 'btn btn-success'
            ]
        );
        ?>

        </div>

    <?php ActiveForm::end(); ?>

</div>

