<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use app\models\User;

/**
 * This is the base-model class for table "instalation_generator".
 *
 * @property string $submission_id
 * @property integer $subtype_id
 * @property string $capacity
 * @property string $capacity_unit
 * @property string $test_capacity
 * @property string $test_capacity_unit
 * @property string $unit_number
 * @property string $turbine_serial_number
 * @property string $generator_serial_number
 * @property string $unit
 * @property integer $fuel_id
 * @property integer $module_quantity
 * @property string $each_module_capacity
 * @property integer $inverter_quantity
 * @property string $each_inverter_capacity
 * @property string $calorific_value
 * @property integer $calorific_value_file_id
 * @property string $fuel_consumption_hhv
 * @property string $fuel_consumption_lhv
 * @property integer $fuel_consumption_rate_file_id
 * @property string $sfc
 *
 *
 * @property \app\models\Fuel $fuel
 * @property \app\models\Submission $submission
 * @property \app\models\InstalationSubtype $subtype
 *
 */
abstract class InstalationGenerator extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'instalation_generator';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['submission_id'], 'required'],
            [['submission_id', 'subtype_id', 'fuel_id', 'module_quantity', 'inverter_quantity', 'calorific_value_file_id', 'fuel_consumption_rate_file_id'], 'integer'],
            [['capacity', 'test_capacity'], 'number'],
            [['capacity_unit', 'test_capacity_unit'], 'string', 'max' => 8],
            [['unit_number'], 'string', 'max' => 32],
            [['turbine_serial_number', 'generator_serial_number', 'each_module_capacity', 'each_inverter_capacity', 'calorific_value', 'fuel_consumption_hhv', 'fuel_consumption_lhv', 'sfc'], 'string', 'max' => 64],
            [['unit'], 'string', 'max' => 128],
            [['submission_id'], 'unique'],
            [['fuel_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Fuel::className(), 'targetAttribute' => ['fuel_id' => 'id']],
            [['submission_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Submission::className(), 'targetAttribute' => ['submission_id' => 'id']],
            [['subtype_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InstalationSubtype::className(), 'targetAttribute' => ['subtype_id' => 'id']],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFuel()
    {
        return $this->hasOne(\app\models\Fuel::className(), ['id' => 'fuel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubmission()
    {
        return $this->hasOne(\app\models\Submission::className(), ['id' => 'submission_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubtype()
    {
        return $this->hasOne(\app\models\InstalationSubtype::className(), ['id' => 'subtype_id']);
    }

}
