<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use app\models\User;

/**
 * This is the base-model class for table "instalation_transmission".
 *
 * @property string $submission_id
 * @property integer $subtype_id
 * @property integer $ownership_status
 * @property integer $network_id
 * @property string $jtet
 * @property string $jtt
 * @property integer $voltage_id
 * @property string $power_house_capacity
 * @property string $tower
 * @property string $line_bay
 * @property string $bus_coupler_bay
 * @property string $transformer_bay
 * @property string $power_breaker_capacity
 * @property string $power_transformer_capacity
 *
 *
 * @property \app\models\TransmissionNetwork $network
 * @property \app\models\Submission $submission
 * @property \app\models\InstalationSubtype $subtype
 * @property \app\models\Voltage $voltage
 *
 */
abstract class InstalationTransmission extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'instalation_transmission';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['submission_id'], 'required'],
            [['submission_id', 'subtype_id', 'ownership_status', 'network_id', 'voltage_id'], 'integer'],
            [['jtet', 'jtt'], 'string', 'max' => 128],
            [['power_house_capacity'], 'string', 'max' => 32],
            [['tower', 'line_bay', 'bus_coupler_bay', 'transformer_bay', 'power_breaker_capacity', 'power_transformer_capacity'], 'string', 'max' => 64],
            [['submission_id'], 'unique'],
            [['network_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TransmissionNetwork::className(), 'targetAttribute' => ['network_id' => 'id']],
            [['submission_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Submission::className(), 'targetAttribute' => ['submission_id' => 'id']],
            [['subtype_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InstalationSubtype::className(), 'targetAttribute' => ['subtype_id' => 'id']],
            [['voltage_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Voltage::className(), 'targetAttribute' => ['voltage_id' => 'id']],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNetwork()
    {
        return $this->hasOne(\app\models\TransmissionNetwork::className(), ['id' => 'network_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubmission()
    {
        return $this->hasOne(\app\models\Submission::className(), ['id' => 'submission_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubtype()
    {
        return $this->hasOne(\app\models\InstalationSubtype::className(), ['id' => 'subtype_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVoltage()
    {
        return $this->hasOne(\app\models\Voltage::className(), ['id' => 'voltage_id']);
    }

}
