<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use app\models\User;

/**
 * This is the base-model class for table "instalation_utilization".
 *
 * @property string $submission_id
 * @property integer $subtype_id
 * @property string $substation_transformer_kva
 * @property string $connected_power_kva
 * @property integer $medium_voltage_connecting_panel_quantity
 * @property integer $low_voltage_connecting_panel_quantity
 * @property string $electricity_provider
 *
 *
 * @property \app\models\Submission $submission
 * @property \app\models\InstalationSubtype $subtype
 *
 */
abstract class InstalationUtilization extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'instalation_utilization';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['submission_id'], 'required'],
            [['submission_id', 'subtype_id', 'medium_voltage_connecting_panel_quantity', 'low_voltage_connecting_panel_quantity'], 'integer'],
            [['substation_transformer_kva', 'connected_power_kva'], 'number'],
            [['electricity_provider'], 'string', 'max' => 512],
            [['submission_id'], 'unique'],
            [['submission_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Submission::className(), 'targetAttribute' => ['submission_id' => 'id']],
            [['subtype_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InstalationSubtype::className(), 'targetAttribute' => ['subtype_id' => 'id']],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubmission()
    {
        return $this->hasOne(\app\models\Submission::className(), ['id' => 'submission_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubtype()
    {
        return $this->hasOne(\app\models\InstalationSubtype::className(), ['id' => 'subtype_id']);
    }

}
