<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use app\models\User;

/**
 * This is the base-model class for table "instalation_distribution".
 *
 * @property string $submission_id
 * @property integer $subtype_id
 * @property integer $ownership_status
 * @property string $distribution_region
 * @property string $jtm_length_kms
 * @property string $sktm_length_ms
 * @property string $sutm_length_ms
 * @property string $jtr_length_kms
 * @property string $sktr_length_ms
 * @property string $sutr_length_ms
 * @property string $substation_capacity_kva
 * @property integer $voltage_id
 * @property integer $substation_quantity
 * @property integer $panel_quantity
 * @property string $short_circuit_capacity_a
 *
 *
 * @property \app\models\Submission $submission
 * @property \app\models\InstalationSubtype $subtype
 *
 */
abstract class InstalationDistribution extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'instalation_distribution';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['submission_id'], 'required'],
            [['submission_id', 'subtype_id', 'ownership_status', 'voltage_id', 'substation_quantity', 'panel_quantity'], 'integer'],
            [['jtm_length_kms', 'sktm_length_ms', 'sutm_length_ms', 'jtr_length_kms', 'sktr_length_ms', 'sutr_length_ms', 'substation_capacity_kva', 'short_circuit_capacity_a'], 'number'],
            [['distribution_region'], 'string', 'max' => 4],
            [['submission_id'], 'unique'],
            [['submission_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Submission::className(), 'targetAttribute' => ['submission_id' => 'id']],
            [['subtype_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\InstalationSubtype::className(), 'targetAttribute' => ['subtype_id' => 'id']],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubmission()
    {
        return $this->hasOne(\app\models\Submission::className(), ['id' => 'submission_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubtype()
    {
        return $this->hasOne(\app\models\InstalationSubtype::className(), ['id' => 'subtype_id']);
    }

}
