<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "submission".
 *
 * @property string $id
 * @property integer $is_deleted
 * @property string $agenda_number
 * @property integer $progress_status
 * @property string $examination_date
 * @property integer $owner_id
 * @property string $instalation_name
 * @property string $instalation_location
 * @property string $instalation_country_id
 * @property string $instalation_province_id
 * @property string $instalation_regency_id
 * @property string $instalation_latitude
 * @property string $instalation_longitude
 * @property integer $bussiness_type_id
 * @property integer $sbu_id
 * @property integer $technical_pic_id
 * @property integer $technical_personel_id
 * @property string $report_number
 * @property integer $report_file_id
 * @property integer $requested_at
 * @property integer $requested_by
 * @property integer $registering_at
 * @property integer $registering_by
 * @property integer $registered_at
 * @property integer $registered_by
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\BussinessType $bussinessType
 * @property \app\models\Owner $owner
 * @property \app\models\Sbu $sbu
 * @property \app\models\TechnicalPersonel $technicalPersonel
 * @property \app\models\TechnicalPic $technicalPic
 *
 */
abstract class Submission extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'submission';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'progress_status', 'owner_id', 'instalation_country_id', 'instalation_province_id', 'instalation_regency_id', 'bussiness_type_id', 'sbu_id', 'technical_pic_id', 'technical_personel_id', 'report_file_id', 'requested_at', 'requested_by', 'registering_at', 'registering_by', 'registered_at', 'registered_by'], 'integer'],
            [['examination_date'], 'safe'],
            [['instalation_location'], 'string'],
            [['instalation_latitude', 'instalation_longitude'], 'number'],
            [['agenda_number', 'report_number'], 'string', 'max' => 64],
            [['instalation_name'], 'string', 'max' => 128],
            [['bussiness_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\BussinessType::className(), 'targetAttribute' => ['bussiness_type_id' => 'id']],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Owner::className(), 'targetAttribute' => ['owner_id' => 'id']],
            [['sbu_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Sbu::className(), 'targetAttribute' => ['sbu_id' => 'id']],
            [['technical_personel_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TechnicalPersonel::className(), 'targetAttribute' => ['technical_personel_id' => 'id']],
            [['technical_pic_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TechnicalPic::className(), 'targetAttribute' => ['technical_pic_id' => 'id']],
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBussinessType()
    {
        return $this->hasOne(\app\models\BussinessType::className(), ['id' => 'bussiness_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(\app\models\Owner::className(), ['id' => 'owner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSbu()
    {
        return $this->hasOne(\app\models\Sbu::className(), ['id' => 'sbu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTechnicalPersonel()
    {
        return $this->hasOne(\app\models\TechnicalPersonel::className(), ['id' => 'technical_personel_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTechnicalPic()
    {
        return $this->hasOne(\app\models\TechnicalPic::className(), ['id' => 'technical_pic_id']);
    }




}
