<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "technical_pic".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $address
 * @property string $country_id
 * @property string $province_id
 * @property string $regency_id
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\models\Submission[] $submissions
 *
 */
abstract class TechnicalPic extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'technical_pic';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'blameable' => [
                'class' => BlameableBehavior::className(),
            ],
            'timestamp' => [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'country_id', 'province_id', 'regency_id'], 'integer'],
            [['address'], 'string'],
            [['name'], 'string', 'max' => 512],
            [['phone', 'email'], 'string', 'max' => 64],
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubmissions()
    {
        return $this->hasMany(\app\models\Submission::className(), ['technical_pic_id' => 'id']);
    }




}
