<?php

use app\dictionaries\OwnershipStatus;
use app\models\InstalationTransmission;
use dmstr\bootstrap\Tabs;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model InstalationTransmission */
?>
<div class="instalation-transmission-view">

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'subtype_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'subtype.name', '<span class="label label-warning">?</span>'),
            ],
            [
                'attribute' => 'ownership_status',
                'format' => 'html',
                'value' => OwnershipStatus::getLabel($model->ownership_status),
            ],
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'network_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'network.name', '<span class="label label-warning">?</span>'),
            ],
            // generated by app\generator\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'voltage_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'voltage.name', '<span class="label label-warning">?</span>'),
            ],
            'jtet',
            'jtt',
            'power_house_capacity',
            'tower',
            'line_bay',
            'bus_coupler_bay',
            'transformer_bay',
            'power_breaker_capacity',
            'power_transformer_capacity',
        ],
    ]);
    ?>

</div>
