<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\location\models\base;

use Yii;
use dosamigos\translateable\TranslateableBehavior;

/**
 * This is the base-model class for table "location_place".
 *
 * @property string $id
 * @property integer $type_id
 * @property string $sublocation_of
 * @property double $latitude
 * @property double $longitude
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\modules\location\models\LocationPlace $sublocationOf
 * @property \app\modules\location\models\LocationPlace[] $locationPlaces
 * @property \app\modules\location\models\LocationType $type
 * @property \app\modules\location\models\LocationSublocationCounter[] $locationSublocationCounters
 * @property string $aliasModel
 */
abstract class LocationPlace extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_place';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('location-model', 'LocationPlaces');
        }else{
            return Yii::t('location-model', 'LocationPlace');
        }
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
                'translationAttributes' => [
                    'name'
                ]
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_id', 'sublocation_of', 'created_at', 'created_by', 'updated_at', 'updated_by'], 'integer'],
            [['latitude', 'longitude'], 'number'],
            [['sublocation_of'], 'exist', 'skipOnError' => true, 'targetClass' => LocationPlace::className(), 'targetAttribute' => ['sublocation_of' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => LocationType::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('location-model', 'ID'),
            'type_id' => Yii::t('location-model', 'Type ID'),
            'sublocation_of' => Yii::t('location-model', 'Sublocation Of'),
            'latitude' => Yii::t('location-model', 'Latitude'),
            'longitude' => Yii::t('location-model', 'Longitude'),
            'created_at' => Yii::t('location-model', 'Created At'),
            'created_by' => Yii::t('location-model', 'Created By'),
            'updated_at' => Yii::t('location-model', 'Updated At'),
            'updated_by' => Yii::t('location-model', 'Updated By'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('location-model', 'ID'),
            'type_id' => Yii::t('location-model', 'Type Id'),
            'sublocation_of' => Yii::t('location-model', 'Sublocation Of'),
            'latitude' => Yii::t('location-model', 'Latitude'),
            'longitude' => Yii::t('location-model', 'Longitude'),
            'created_at' => Yii::t('location-model', 'Created At'),
            'created_by' => Yii::t('location-model', 'Created By'),
            'updated_at' => Yii::t('location-model', 'Updated At'),
            'updated_by' => Yii::t('location-model', 'Updated By'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSublocationOf()
    {
        return $this->hasOne(\app\modules\location\models\LocationPlace::className(), ['id' => 'sublocation_of']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationPlaces()
    {
        return $this->hasMany(\app\modules\location\models\LocationPlace::className(), ['sublocation_of' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\app\modules\location\models\LocationType::className(), ['id' => 'type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationSublocationCounters()
    {
        return $this->hasMany(\app\modules\location\models\LocationSublocationCounter::className(), ['place_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(\app\modules\location\models\LocationPlaceLang::className(), ['place_id' => 'id']);
    }



}
