<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\location\models\base;

use Yii;

/**
 * This is the base-model class for table "location_sublocation_counter".
 *
 * @property string $id
 * @property string $place_id
 * @property integer $type_id
 * @property integer $quantity
 *
 * @property \app\modules\location\models\LocationPlace $place
 * @property \app\modules\location\models\LocationType $type
 * @property string $aliasModel
 */
abstract class LocationSublocationCounter extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_sublocation_counter';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('location-model', 'LocationSublocationCounters');
        }else{
            return Yii::t('location-model', 'LocationSublocationCounter');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['place_id', 'type_id', 'quantity'], 'integer'],
            [['place_id'], 'exist', 'skipOnError' => true, 'targetClass' => LocationPlace::className(), 'targetAttribute' => ['place_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => LocationType::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('location-model', 'ID'),
            'place_id' => Yii::t('location-model', 'Place ID'),
            'type_id' => Yii::t('location-model', 'Type ID'),
            'quantity' => Yii::t('location-model', 'Quantity'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('location-model', 'ID'),
            'place_id' => Yii::t('location-model', 'Place Id'),
            'type_id' => Yii::t('location-model', 'Type Id'),
            'quantity' => Yii::t('location-model', 'Quantity'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlace()
    {
        return $this->hasOne(\app\modules\location\models\LocationPlace::className(), ['id' => 'place_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\app\modules\location\models\LocationType::className(), ['id' => 'type_id']);
    }




}
