<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\location\models\base;

use Yii;
use dosamigos\translateable\TranslateableBehavior;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "location_type".
 *
 * @property integer $id
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \app\modules\location\models\LocationPlace[] $locationPlaces
 * @property \app\modules\location\models\LocationSublocationCounter[] $locationSublocationCounters
 * @property string $aliasModel
 */
abstract class Type extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_type';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
                'translationAttributes' => [
                    'name',
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('modules/location/models', 'ID'),
            'created_at' => Yii::t('modules/location/models', 'Created At'),
            'created_by' => Yii::t('modules/location/models', 'Created By'),
            'updated_at' => Yii::t('modules/location/models', 'Updated At'),
            'updated_by' => Yii::t('modules/location/models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationPlaces()
    {
        return $this->hasMany(\app\modules\location\models\LocationPlace::className(), ['type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationSublocationCounters()
    {
        return $this->hasMany(\app\modules\location\models\LocationSublocationCounter::className(), ['type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        return $this->hasMany(\app\modules\location\models\LocationTypeLang::className(), ['type_id' => 'id']);
    }



}
